server {
    listen 80;

    # 1. Запросы к бэкенду (все, что начинается с /api)
    location /api/ {
        proxy_pass http://data-api:8080/; # Слэш в конце очистит префикс /api
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 2. Раздача статики Vite (вместо прокси на Node.js)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html; # Перенаправляет все запросы на index.html для SPA
    }
}